name: Build and release the module.

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'paymenterio.zip'
          directory: 'paymenterio'
          exclusions: '*.git* *.idea* /*node_modules/* .editorconfig'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "paymenterio.zip"
          token: ${{ secrets.GITHUB_TOKEN }}